-- Generated by scripts/hypr2lua.
-- Source: omarchy-flat-dracula-theme/hyprland.conf

hl.config({
  general = {
    col = {
      active_border = {
        colors = { "rgba(bd93f9ee)", "rgba(6272a4ee)" },
        angle = 65,
      },
      inactive_border = "rgba(44475aff)",
    },
  },
  decoration = {
    rounding = 0,
    shadow = {
      enabled = true,
      range = 12,
      render_power = 6,
      offset = "0 0",
      color = "rgba(BD93F9ee)",
      color_inactive = "rgba(6272A433)",
    },
  },
})

hl.window_rule({
  name = "windowrule-1",
  opacity = "1 0.95",
  match = {
    class = ".*",
  },
})
hl.window_rule({
  name = "windowrule-2",
  no_dim = true,
  opacity = "1.0 override 1.0 override",
  match = {
    class = "(^brave-youtube\\.com__-Default$)",
  },
})
hl.window_rule({
  name = "windowrule-gimp",
  tag = "-default-opacity",
  no_dim = true,
  opacity = "1.0 override 1.0 override 1.0 override",
  match = {
    class = "^gimp$",
  },
})
hl.window_rule({
  name = "windowrule-3",
  no_dim = true,
  opacity = "1.0 override 1.0 override",
  match = {
    class = "(^brave-www\\.netflix\\.com__browse-Default$)",
  },
})
